### ISSUE TITLE
can't install courier-imap

### ISSUE THREAD

**Issue by hats0id** [johankok/courier-repo#1]
Hello dear. I have tried yum install courier-imap from your repository - but got this error:

Resolving Dependencies
--> Running transaction check
---> Package courier-imap.x86_64 0:5.0.10-2.el7 will be installed
--> Processing Dependency: courier-authlib >= 0.60.6.20080629 for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourier-unicode.so.4()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauth.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthcommon.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthsasl.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libfam.so.0()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Running transaction check
---> Package courier-authlib.x86_64 0:0.71.0-1.el7 will be installed
--> Processing Dependency: /usr/bin/expect for package: courier-authlib-0.71.0-1.el7.x86_64
---> Package courier-imap.x86_64 0:5.0.10-2.el7 will be installed
--> Processing Dependency: libcourierauth.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthcommon.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthsasl.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
---> Package courier-unicode.x86_64 0:2.1.1-1.el7 will be installed
---> Package gamin.x86_64 0:0.1.10-16.el7 will be installed
--> Running transaction check
---> Package courier-imap.x86_64 0:5.0.10-2.el7 will be installed
--> Processing Dependency: libcourierauth.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthcommon.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthsasl.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
---> Package expect.x86_64 0:5.45-14.el7_1 will be installed
--> Processing Dependency: libtcl8.5.so()(64bit) for package: expect-5.45-14.el7_1.x86_64
--> Running transaction check
---> Package courier-imap.x86_64 0:5.0.10-2.el7 will be installed
--> Processing Dependency: libcourierauth.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthcommon.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
--> Processing Dependency: libcourierauthsasl.so()(64bit) for package: courier-imap-5.0.10-2.el7.x86_64
---> Package tcl.x86_64 1:8.5.13-8.el7 will be installed
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: courier-imap-5.0.10-2.el7.x86_64 (copr:copr.fedorainfracloud.org:johan:courier-repo)
           Requires: libcourierauth.so()(64bit)
Error: Package: courier-imap-5.0.10-2.el7.x86_64 (copr:copr.fedorainfracloud.org:johan:courier-repo)
           Requires: libcourierauthsasl.so()(64bit)
Error: Package: courier-imap-5.0.10-2.el7.x86_64 (copr:copr.fedorainfracloud.org:johan:courier-repo)
           Requires: libcourierauthcommon.so()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Can you help me to fix this error? Thank you in advance.

**Comment by hats0id** [comment]
@johankok please help

**Comment by johankok** [comment]
> Can you help me to fix this error?

Sure! I've updated the packages to the latest release and that fixed this dependency issue. Can you retry installing the package? You might need to cleanup the yum cache (with `yum clean all`) first. You should see yum installing courier-imap version 5.1.2 without problem.

**Comment by hats0id** [comment]
> > Can you help me to fix this error?
> 
> Sure! I've updated the packages to the latest release and that fixed this dependency issue. Can you retry installing the package? You might need to cleanup the yum cache (with `yum clean all`) first. You should see yum installing courier-imap version 5.1.2 without problem.

Yes - works like a charm. Thank you very much.

**Comment by johankok** [comment]
Thanks!
