### ISSUE TITLE
cannot install on EL8, missing libcourier-unicode.so.4

### ISSUE THREAD

**Issue by evert-mouw** [johankok/courier-repo#2]
```
# dnf install maildrop
Last metadata expiration check: 4:23:55 ago on Mon 18 Oct 2021 10:22:48 AM CEST.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libcourier-unicode.so.4()(64bit) needed by maildrop-3.0.0-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
I also tried to install `courier-unicode` first. That doesn't make any difference. Also `--nobest` doesn't help.
My system is a fully updated Oracle Linux 8.4 instance (RHEL clone) with these repos:

```
# dnf repolist
repo id                                           repo name
copr:copr.fedorainfracloud.org:johan:courier-repo Copr repo for courier-repo owned by johan
dovecot-2.3-latest                                Dovecot 2.3 CentOS 8 - x86_64
epel                                              Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                      Extra Packages for Enterprise Linux Modular 8 - x86_64
ol8_UEKR6                                         Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux 8 (x86_64)
ol8_appstream                                     Oracle Linux 8 Application Stream (x86_64)
ol8_baseos_latest                                 Oracle Linux 8 BaseOS Latest (x86_64)
ol8_codeready_builder                             Oracle Linux 8 CodeReady Builder (x86_64) - Unsupported
zfs-kmod                                          ZFS on Linux for EL8 - kmod

```

the copr repo has `baseurl=https://download.copr.fedorainfracloud.org/results/johan/courier-repo/epel-8-$basearch/`

Probably building from source would get me a maildrop but maybe I did something wrong and as I'm lazy I prefer to use an existing repo ;-)

**Comment by johankok** [comment]
It's not you, it's me :) 
I stopped using maildrop a while back and I did not update the package.

```
[johan@courier-test-1 ~]$ rpm -q --provides courier-unicode
courier-unicode = 2.2.3-1.el8
courier-unicode(x86-64) = 2.2.3-1.el8
libcourier-unicode.so.7()(64bit)
```
That's `libcourier-unicode.so.7` instead of `libcourier-unicode.so.4`. Let me try updating maildrop to the latest version, a new build would probably resolve this.

**Comment by johankok** [comment]
A new build (maildrop-3.0.3) should be available for EL8. You may have to issue `dnf clean all` to force reloading of the repo.

**Comment by evert-mouw** [comment]
Now it Just Works (TM), great stuff :-)

Really I should upgrade my maildrop script to Sieve as I'm already using Dovecot, but maildrop served me well in the past and the script is already there. For a small personal server, I also like how easy it is to use external scripts with maildrop. Anyway, issue closed & thanks!
